services:
  db:
    image: postgres:latest
    restart: always
    env_file: ".env"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  s3:
    image: quay.io/minio/minio
    restart: always
    volumes:
      - s3_data:/var/lib/minio/data
    command: server /var/lib/minio/data --console-address ":9001"
    env_file: ".env"
    ports:
      - "9000:9000"
      - "9001:9001"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    image: gitea.dojo-vernier.ts.net/duelvault:dev
    depends_on:
      - db
      - s3
    ports:
      - "3000:3000"
    env_file: ".env"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
  s3_data:
